export default chatFaceData=[
    {
        id:1,
        name:'Adam',
        image:'https://phattriennanglucso.com/chatface.png',
        primary:'#3B96D2',
        secondary:''
    },
    {
        id:2,
        name:'Adam',
        image:'https://phattriennanglucso.com/chatface.png',
        primary:'#3B96D2',
        secondary:''
    },
    {
        id:3,
        name:'Adam',
        image:'https://phattriennanglucso.com/chatface.png',
        primary:'#3B96D2',
        secondary:''
    },
]